

 ## Background
  
  ### Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset).
  
 ## Data
  
  ### The training data for this project are available here:
  
  ### https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv
  
  ### The test data are available here:
  
  ### https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv
  
  ### The data for this project come from this source: http://groupware.les.inf.puc-rio.br/har. If you use the document you create for this class for any purpose please cite them as they have been very generous in allowing their data to be used for this kind of assignment.

## Report describing 

## How you built your model, 

* LOADING REQUIRED R-PACAKGES (caret,randomForest,gbm,rpart)
* set working dir and load train and test pml data into r environment
* Partition of training dataset ino training and testing probability 0.6:0.4 and set a fixed seed for reproducible of result
* Variable identification for the exercise (i.e identification of non-zero column variables)
* It is a robust method for estimating accuracy, and the size of k and tune the amount of bias in the estimate, with popular values set to 3, 5, 7 and 10.Because of time of execution data sample I used K-fold of 3.
* Building of the model for prediction.: There are several approaches of building model in predictive machine learning based on the outcome and nature of the predicting variable (depenedent variable) that will tell if is supervised or unsupervised predictive machine learning. This exercise is a classification predictive machine learning the most commonly used methods are considered in this exercise. These are: (1). Decision trees with CART (rpart). (2). Stochastic gradient boosting trees (gbm).(3). Random forest decision trees (rf) 
* Reason for selecting the 3 model for this exercise. Because the dependent variables are classe (factors) i.e nominal data. Meaning that is classification problem.
* The out of sample result show a robust and accuracy result of the three choice model and random forest and gradient boosting model outperformed CART. And random forest is the best for this dataset for this exercise.
* Prediction of 20 cases with the champion model i.e random forest
* Conclusion

## How you used cross validation, 

* It is a robust method for estimating accuracy, and the size of k and tune the amount of bias in the estimate, with popular values set to 3, 5, 7 and 10.Because of time of execution data sample I used K-fold of 3.

## What you think the expected out of sample error is, and 
* The out of sample result show a robust and accuracy result of the three choice model and random forest and gradient boosting model outperformed CART. And random forest is the best for this dataset for this exercise.

## Why you made the choices you did. You will also use your prediction model to predict 20 different test cases.
* The result from the 3-model fits and accuracy result, shows that GBM (gradient boosting method) and RF (random forest) both perform better for the avaliable dataset than the CART model. And the champion model is the RF model fit for this exercise




